### ISSUE TITLE
switch to remote sessions

### ISSUE THREAD

**Issue by krahser** [farfanoide/yat.sh#11]
It's very usefull inside a local session to move to another session, just calling to it.

```yat.sh another_session```

In the code this is done with a switch -> https://github.com/farfanoide/yat.sh/blob/96396d6f03a47ce0bbf3e92fae949dc6de1914a2/libexec/yatsh-load#L38

my question is, how can we provide this switch functionality to remote session?
Doing a detach of the current client stops the script of connecting to the remote session.

I bet you have some good idea on how to approach that.

Thanks!

**Comment by farfanoide** [comment]
incredibly difficult to achieve afaik with current implementation because  when you launch a remote session there's no knowledge of that in your local computer.

workaround is to have a local session which opens a remote session.
note that when you do this you'd have to send the tmux prefix 2 times to actually talk to the remote session...
i know, not ideal but it works.

**Comment by krahser** [comment]
Thanks
